<?php 

/**
 * @file (Un)installation and schema hooks for scheduled_actions_node module.
 */

/**
 * Implements hook_uninstall().
 */
function scheduled_actions_node_uninstall() {
  //Delete vars
  $node_types = node_type_get_names();
  foreach ($node_types as $type => $name) {
    variable_del('scheduled_actions_node_enable' . $type);
    variable_del('scheduled_actions_node_actions' . $type);
  }
  
  variable_del('scheduled_actions_node_date_format');
}