<?php
/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implements hook_help().
 */
function valuvet_rich_forms_help($path, $arg) {
  /* INFO:
   * The help hook is for displaying helpful messages at the top of pages indicated
   * by $section to further explain how they work. Adding certain "keywords" to the end of
   * a given path (like admin/modules#description) will cause this text to display elsewhere
   * in the page as well (in this case, in the description section for the given module).
   */
  switch ($path) {
    case 'admin/help#valuvet_rich_forms':
      return t("This module is a custom one and has no configuration options. All is hardcoded in the module file. Basically it adds javascript into forms to add some UX sugar to them.");
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function valuvet_rich_forms_form_property_node_form_alter(&$form, &$form_state, $form_id) {
  // if user is admin, don't bother him with validation...
  if (user_access('administer nodes')) return;
  // else add behaviors
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/jquery.price_format.js', 'file');
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/valuvet_rich_property_form.js', 'file');
  drupal_add_css(drupal_get_path('module', 'valuvet_rich_forms').'/css/valuvet_rich_property_form.css', 'file');
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function valuvet_rich_forms_form_career_node_form_alter(&$form, &$form_state, $form_id) {
  // if user is admin, don't bother him with validation...
  if (user_access('administer nodes')) return;
  // else add behaviors
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/jquery.price_format.js', 'file');
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/valuvet_rich_career_form.js', 'file');
  drupal_add_css(drupal_get_path('module', 'valuvet_rich_forms').'/css/valuvet_rich_career_form.css', 'file');
}

function valuvet_rich_forms_form_alter(&$form, &$form_state, $form_id) {        
  switch ($form_id) {
    case 'property_node_form':        
      $form['#prefix'] = '<div id="replace-element">';
      $form['#suffix'] = '</div>' ;
      

      foreach ($form['field_property_package']['und']['#options'] as $product_id=>$item){
        $product = commerce_product_load($product_id);
        $price = entity_metadata_wrapper('commerce_product', $product)->commerce_price->value();      
        $price_display = commerce_currency_format($price['amount'], $price['currency_code'], $product);
        $form['field_property_package']['und']['#options'][$product_id] = $form['field_property_package']['und']['#options'][$product_id] . ' - ' . $price_display;          
      }
      
      break;
  
     case 'commerce_checkout_form_checkout':
         global $user;                  
         $user = user_load($user->uid);
         //print_r($user);
         if($user->field_user_name['und'][0]['safe_value'] != '' || $user->field_user_last_name['und'][0]['safe_value'] != ''){
           $form['customer_profile_billing']['commerce_customer_address']['und'][0]['name_block']['name_line']['#value'] = $user->field_user_name['und'][0]['safe_value'] . ' ' . $user->field_user_last_name['und'][0]['safe_value'];
         }
         if($user->field_user_address['und'][0]['safe_value'] != ''){
           $form['customer_profile_billing']['commerce_customer_address']['und'][0]['street_block']['thoroughfare']['#value'] = $user->field_user_address['und'][0]['safe_value'];
         }         
         if($user->field_user_city_suburb['und'][0]['safe_value'] != ''){
           $form['customer_profile_billing']['commerce_customer_address']['und'][0]['locality_block']['locality']['#value'] = $user->field_user_city_suburb['und'][0]['safe_value'];
         }                  
         if($user->field_user_state['und'][0]['safe_value'] != ''){
           $form['customer_profile_billing']['commerce_customer_address']['und'][0]['locality_block']['administrative_area']['#value'] = $user->field_user_state['und'][0]['safe_value'];
         }          
         if($user->field_user_post_code['und'][0]['safe_value'] != ''){
           $form['customer_profile_billing']['commerce_customer_address']['und'][0]['locality_block']['postal_code']['#value'] = $user->field_user_post_code['und'][0]['safe_value'];
         }                   
         break;
  }
  return;
}

function valuvet_rich_forms_field_widget_form_alter(&$element, &$form_state, $context) {
  // If this is an image field type
  if ($context['field']['type'] == 'image') {
    // Loop through the element children (there will always be at least one).
    foreach (element_children($element) as $key => $child) {
      // Add the new process function to the element
      $element[$key]['#process'][] = 'valuvet_rich_forms_image_field_widget_process';
    }
  }
}

function valuvet_rich_forms_image_field_widget_process($element, &$form_state, $form) {
  // Change the title field to a textarea
  $element['title']['#description'] = t('The text is used as the photo title.');

  // Return the altered element
  return $element;
}