<?php
/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implements hook_help().
 */
function valuvet_rich_forms_help($path, $arg) {
  /* INFO:
   * The help hook is for displaying helpful messages at the top of pages indicated
   * by $section to further explain how they work. Adding certain "keywords" to the end of
   * a given path (like admin/modules#description) will cause this text to display elsewhere
   * in the page as well (in this case, in the description section for the given module).
   */
  switch ($path) {
    case 'admin/help#valuvet_rich_forms':
      return t("This module is a custom one and has no configuration options. All is hardcoded in the module file. Basically it adds javascript into forms to add some UX sugar to them.");
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function valuvet_rich_forms_form_property_node_form_alter(&$form, &$form_state, $form_id) {
  // if user is admin, don't bother him with validation...
  if (user_access('administer nodes')) return;
  // else add behaviors
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/jquery.price_format.js', 'file');
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/valuvet_rich_property_form.js', 'file');
  drupal_add_css(drupal_get_path('module', 'valuvet_rich_forms').'/css/valuvet_rich_property_form.css', 'file');
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function valuvet_rich_forms_form_career_node_form_alter(&$form, &$form_state, $form_id) {
  // if user is admin, don't bother him with validation...
  if (user_access('administer nodes')) return;
  // else add behaviors
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/jquery.price_format.js', 'file');
  drupal_add_js(drupal_get_path('module', 'valuvet_rich_forms').'/js/valuvet_rich_career_form.js', 'file');
  drupal_add_css(drupal_get_path('module', 'valuvet_rich_forms').'/css/valuvet_rich_career_form.css', 'file');
}